<a href="https://colab.research.google.com/github/yg-kim-korean/fastcampusAI/blob/main/pytorch_%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
nums.shape

torch.Size([9])

In [4]:
type(nums)

torch.Tensor

In [5]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
type(nums)

torch.Tensor

In [7]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
randoms = torch.rand((3,3))
randoms

tensor([[0.4433, 0.0650, 0.7869],
        [0.8431, 0.6836, 0.6235],
        [0.2832, 0.6466, 0.1797]])

In [10]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
 torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
zeros.size()

torch.Size([3, 3])

In [14]:
#Operations
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [15]:
nums + nums 

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [16]:
result = torch.add(nums,10)

In [17]:
result.numpy()

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [18]:
#View
range_nums = torch.arange(9).reshape(3,3)

In [19]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
range_nums.view(1,9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [22]:
arr = np.array([1,1,1])

In [23]:
arr_torch = torch.from_numpy(arr)

In [24]:
arr_torch.float()

tensor([1., 1., 1.])

In [25]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [26]:
arr_torch.to(device)

tensor([1, 1, 1])

In [27]:
#AutoGrad
x = torch.ones(2,2, requires_grad=True)

In [28]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)