<a href="https://colab.research.google.com/github/yg-kim-korean/fastcampusAI/blob/main/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
print("gell")

gell


In [4]:
import torch

In [5]:
import numpy as np

In [6]:
arr = np.array(5)
arr.shape

()

In [7]:
arr.ndim

0

In [8]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
zeros=np.zeros(1)
zeros

array([0.])

In [10]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [12]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [14]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
data = np.random.randn(3,3)
data

array([[ 0.64429459, -3.42581008, -1.40482663],
       [-0.68281202, -0.79175731, -0.84905383],
       [-2.39667728,  0.62916871,  1.11913582]])

In [16]:
data <= 0

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [17]:
data[data<=0] =1 
data

array([[0.64429459, 1.        , 1.        ],
       [1.        , 1.        , 1.        ],
       [1.        , 0.62916871, 1.11913582]])

In [18]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [21]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [22]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [23]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr = np.random.randint(2, size=27).reshape(3,3,3)
arr_2 = np.random.randint(2, size=9).reshape(3,3)

In [25]:
arr

array([[[0, 1, 1],
        [0, 0, 0],
        [0, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [0, 1, 0]],

       [[1, 0, 0],
        [1, 0, 1],
        [1, 0, 0]]])

In [26]:
arr_2

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 1]])

In [27]:
arr+arr_2

array([[[0, 2, 1],
        [0, 0, 1],
        [1, 1, 2]],

       [[1, 2, 1],
        [1, 1, 2],
        [1, 1, 1]],

       [[1, 1, 0],
        [1, 0, 2],
        [2, 0, 1]]])

In [28]:
np.sum(arr)

15

In [29]:
np.sum(arr+arr_2)

27

In [30]:
np.max(arr)

1

In [31]:
arr = np.array([1,6,3,7,3,2,9])
arr

array([1, 6, 3, 7, 3, 2, 9])

In [32]:
np.argmax(arr)

6

6번째 인덱스가 제일 크다는거

In [33]:
arr= np.array([3,6,5,3,3,1])

In [34]:
np.unique(arr)

array([1, 3, 5, 6])

In [35]:
arr = np.array([[1,2,3],[1,2,3]])

In [36]:
arr.dtype

dtype('int64')

In [40]:
arr = np.array([[1,2,3],[1,2,3]])

In [38]:
arr.shape

(2, 3)

In [42]:
arr.reshape([6]).shape

(6,)

In [43]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3])

In [44]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [48]:
arr = arr.reshape(32,2)
arr.shape

(32, 2)

In [50]:
arr = arr.reshape(-1,2,1)
arr.shape

(32, 2, 1)

In [51]:
arr.shape

(32, 2, 1)

In [53]:
arr = arr.ravel()
arr.shape

(64,)

In [54]:
arr.shape

(64,)

In [55]:
arr=np.expand_dims(arr,-1)
arr.shape

(64, 1)

In [56]:
arr = arr.ravel()

In [57]:
arr.shape

(64,)

In [58]:
arr = np.expand_dims(arr,-1)
arr.shape

(64, 1)