<a href="https://colab.research.google.com/github/yg-kim-korean/fastcampusAI/blob/main/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

In [ ]:
print("gell")

gell


In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
arr = np.array(5)
arr.shape

()

In [ ]:
arr.ndim

0

In [ ]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
zeros=np.zeros(1)
zeros

array([0.])

In [ ]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
data = np.random.randn(3,3)
data

array([[-0.70799009,  1.76817243, -0.2983654 ],
       [-1.41406241, -0.55762827,  0.91210376],
       [-1.7740159 ,  0.45807016,  2.21463631]])

In [ ]:
data <= 0

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

In [ ]:
data[data<=0] =1 
data

array([[1.        , 1.76817243, 1.        ],
       [1.        , 1.        , 0.91210376],
       [1.        , 0.45807016, 2.21463631]])

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [ ]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.random.randint(2, size=27).reshape(3,3,3)
arr_2 = np.random.randint(2, size=9).reshape(3,3)

In [ ]:
arr

array([[[1, 0, 1],
        [0, 1, 1],
        [1, 0, 0]],

       [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 1, 1],
        [1, 1, 0]]])

In [ ]:
arr_2

array([[0, 1, 1],
       [1, 1, 1],
       [1, 0, 1]])

In [ ]:
arr+arr_2

array([[[1, 1, 2],
        [1, 2, 2],
        [2, 0, 1]],

       [[1, 1, 2],
        [1, 2, 1],
        [2, 0, 1]],

       [[0, 1, 2],
        [1, 2, 2],
        [2, 1, 1]]])

In [ ]:
np.sum(arr)

14

In [ ]:
np.sum(arr+arr_2)

35

In [ ]:
np.max(arr)

1

In [ ]:
arr = np.array([1,6,3,7,3,2,9])
arr

array([1, 6, 3, 7, 3, 2, 9])

In [ ]:
np.argmax(arr)

6

6번째 인덱스가 제일 크다는거

In [ ]:
arr= np.array([3,6,5,3,3,1])

In [ ]:
np.unique(arr)

array([1, 3, 5, 6])

In [ ]:
arr = np.array([[1,2,3],[1,2,3]])

In [ ]:
arr.dtype

dtype('int64')